### ISSUE TITLE
accessing the approval link

### ISSUE THREAD

**Issue by quinyx-max** [automatiko-io/automatiko-approval-task#10]
hi
this is a ux issue i think
going to the yaml file and clicking on the approval link for a big environment with multiple deploys per day or dozens of deploys per release day is very impractical. 

- my first suggestion is to have the button to approve/reject right in the pipeline run panel under the approval stage itself
- if that is not possible, having the button in the approval tasks panel
- if all not possible, have the link clickable somewhere in the approval task row

also having the decision result emitted to the stage itself and changing its color could be a nice to have

**Comment by mswiderski** [comment]
thanks for feedback and this is quite common request and while I would like this to progress it is outside of the responsibility of this project and is more about Tekton dashboard. There is an issue open to get this improved and I already shared my view on how this could help approvals. See here https://github.com/tektoncd/dashboard/issues/1970

feel free to comment there too, the more people request this to be improved the better.

With that, I am afraid I won't be able to make anything better on this project level.

As a way to improve the situation, you can use notification channels - email, slack or ms teams to send direct link to the approval task.
