### ISSUE TITLE
About the person who approves

### ISSUE THREAD

**Issue by phenomrascalov** [automatiko-io/automatiko-approval-task#12]
Hello, 
In the structure we have designed, the approval link is being sent to two people via email. 
At the same time, we need to log information about who approves in this structure. 
What approach can we take regarding this matter? Is there a way for us to obtain the email address of the person who approves ?
Thanks for your help.
Best regards.

**Comment by phenomrascalov** [comment]
Hello,
This solves our problem. It sounds perfect. 
Thank you.

**Comment by mswiderski** [comment]
alright, so a image that contains this functionality can be found here `mswiderski/automatiko-approval-task:0.9.0`

In addition, you need to apply new version of CRD that brings in these two result in the definition - https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/v1beta1/approvaltasks.tekton.automatiko.io-v1.yml

let me know if it works as expected and then I will cut new release with it.

**Comment by phenomrascalov** [comment]
It works. Thanks for help :)

**Comment by mswiderski** [comment]
great, thanks for fast confirmation. New release was just published and you can now use official image from `automatiko/automatiko-approval-task:0.9.0`
