### ISSUE TITLE
Missing CPU features

### ISSUE THREAD

**Issue by Bibz87** [automatiko-io/automatiko-approval-task#14]
After updating to version `0.10.0`, the approval task container refuses the start and shows the following error:

```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.
```

According to Quarkus' [docs](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2#native-compilation---work-around-missing-cpu-features) there's a build parameter that can be added to increase the chance of compatibility with older CPUs.

Are the new CPU features required for Approval Task `0.10.0`? If that's not the case, can the image be built with the compatibility flag?

**Comment by mswiderski** [comment]
thanks for reporting. Just build it to be able to test it out - can you give a try `mswiderski/automatiko-approval-task:0.10.1` image and let me know if that solves the problem? If so I will push new official release

**Comment by Bibz87** [comment]
Yes, I can confirm that `mswiderski/automatiko-approval-task:0.10.1` starts and runs properly. Thanks! :)

**Comment by mswiderski** [comment]
fixed with https://github.com/automatiko-io/automatiko-approval-task/commit/3c0c6cb7b3b99e80f99d7cad28738dbdcec072da

now official image for `automatiko/automatiko-approval-task:0.10.1` is pushed to docker hub and ready to be used.
