### ISSUE TITLE
Is it possible to embed approve dialog box in Approval Tasks menu of tekton dashboard?

### ISSUE THREAD

**Issue by hillbun** [automatiko-io/automatiko-approval-task#2]
Is it possible to embed approve dialog box in Approval Tasks menu of tekton dashboard?

So I do not need to open http://automatiko-approval-task.default/ to approve.

**Comment by mswiderski** [comment]
This is definitely something that would make working with approvals way easier but it is more of an issue in Tekton dashboard to allow such integration. Would you mind opening issue there and link me there?

Currently the only integration is via the extension and that is what automatiko approval tasks already provide. Not much I can do without some work done in Tekton dashboard.

**Comment by hillbun** [comment]
I post here
https://github.com/tektoncd/dashboard/issues/2412

**Comment by mswiderski** [comment]
great, thanks, let's continue discussion there, will close this issue.
