### ISSUE TITLE
Pipeline default/approval-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "approvaltask": tasks.tekton.dev "approvaltask" not found

### ISSUE THREAD

**Issue by rajesh-carelon** [automatiko-io/automatiko-approval-task#8]
I have followed the documentation and video but after creating pipeline when I try to run the pipeline run I am facing the below error.

Please help me resolving the issue. As per my understanding I dont require to create approval task help me understand more.

I am using latest code

Error:
Pipeline default/approval-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "approvaltask": tasks.tekton.dev "approvaltask" not found

**Comment by mswiderski** [comment]
looks like you haven't registered the CRD of ApprovalTask - https://github.com/automatiko-io/automatiko-approval-task#install-approval-tasks-crd

Note that this requires cluster admin rights.
In addition, please provide versions of:
- Tekton
- which custom task api version you use - v1alpha1 or v1beta1
- automatiko approval task version

**Comment by rajesh-carelon** [comment]
Hello @mswiderski ,
I have created CRD of approval task, Do I need to modify anything in the CRD of approval task
approvaltasks.tekton.automatiko.io                    2023-04-10T08:46:28Z

1) Tekton versions:

Dashboard:  v0.34.0
Pipelines: v0.46.0
Triggers:  v0.22.1

2) Do I need to configure custom task ?
Can you please provide me with the Yaml file.

But i have tried creating custom task for approval task but its asking for output reference to the approved task.

Not sure whats wrong, For Approval task reference do we need to create approval task or CRD will create it one for you?

3) automatiko approval task version I am using the code from latest which is tag v0.7.0

**Comment by mswiderski** [comment]
Can you share the pipeline file you used?

**Comment by rajesh-carelon** [comment]
Hello @mswiderski 

Please find the pipeline file

`apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: testpipeline2
spec:
  tasks:
    - name: deploy-dev-approval-task
      taskRef:
        apiVersion: tekton.automatiko.io/v1beta1
        kind: ApprovalTask
        name: approvaltask
      params:
        - name: pipeline
          value: "$(context.pipelineRun.name)"
        - name: description
          value: "Approval from pipeline $(context.pipeline.name) for development environment"
        - name: approvers
          value:
            - "Rajesh.Kamsala@carelon.com"
    - name: deploy-dev-approved-task
      when:
        - input: $(tasks.deploy-dev-approval-task.results.decision)
          operator: in
          values: [ "true" ]
      taskRef:
        name: print-decision
      runAfter:
        - deploy-dev-approval-task
      params:
        - name: decision
          value: "APPROVED"
        - name: comment
          value: $(tasks.deploy-dev-approval-task.results.comment)
    - name: deploy-dev-rejected-task
      when:
        - input: $(tasks.deploy-dev-approval-task.results.decision)
          operator: in
          values: [ "false" ]
      taskRef:
        name: print-decision
      runAfter:
        - deploy-dev-approval-task
      params:
        - name: decision
          value: "REJECTED"
        - name: comment
          value: $(tasks.deploy-dev-approval-task.results.comment)`

**Comment by mswiderski** [comment]
ok, so this looks like the default test pipeline. Could it be you are creating it in different namespace? The CRD is namespaces, so you need to make sure where you create pipeline is where you created approval task CRD.

Then the same goes for deployment of the controller which will then watch only selected namespaces, by default it watches `default` namespace.
https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/v1beta1/kubernetes-basic.yml#L171

**Comment by mswiderski** [comment]
can you also look of custom task are enabled, see the config map https://github.com/automatiko-io/automatiko-approval-task#configure-tekton

approval task are based on Tekton's custom task so it is Tekton that transforms it to custom run and then approval task controller is triggered for the custom run.

**Comment by rajesh-carelon** [comment]
Yea its enabled its value as #custom-task-version: v1beta1 
as per the latest code


# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  await-sidecar-readiness: "true"
  custom-task-version: v1beta1
  disable-affinity-assistant: "true"
  disable-creds-init: "false"
  enable-api-fields: stable
  enable-provenance-in-status: "false"
  enable-tekton-oci-bundles: "false"
  enforce-nonfalsifiablity: none
  require-git-ssh-secret-known-hosts: "false"
  resource-verification-mode: skip
  running-in-environment-with-injected-sidecars: "true"
  send-cloudevents-for-runs: "false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"await-sidecar-readiness":"true","custom-task-version":"v1beta1","disable-affinity-assistant":"false","disable-creds-init":"false","enable-api-fields":"stable","enable-provenance-in-status":"false","enable-tekton-oci-bundles":"false","enforce-nonfalsifiablity":"none","require-git-ssh-secret-known-hosts":"false","resource-verification-mode":"skip","running-in-environment-with-injected-sidecars":"true","send-cloudevents-for-runs":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-pipelines"},"name":"feature-flags","namespace":"tekton-pipelines"}}
  creationTimestamp: "2022-11-29T11:09:09Z"
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:await-sidecar-readiness: {}
        f:disable-creds-init: {}
        f:enable-api-fields: {}
        f:enable-provenance-in-status: {}
        f:enable-tekton-oci-bundles: {}
        f:require-git-ssh-secret-known-hosts: {}
        f:resource-verification-mode: {}
        f:running-in-environment-with-injected-sidecars: {}
        f:send-cloudevents-for-runs: {}
      f:metadata:
        f:annotations: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/part-of: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-11-29T11:09:09Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:enforce-nonfalsifiablity: {}
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl
    operation: Update
    time: "2023-04-04T13:42:50Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:custom-task-version: {}
        f:disable-affinity-assistant: {}
    manager: kubectl-edit
    operation: Update
    time: "2023-04-10T08:04:47Z"
  name: feature-flags
  namespace: tekton-pipelines
  resourceVersion: "93329540"
  uid: 0b4f0de0-61e8-4c7c-803a-3d4fac010c68

**Comment by rajesh-carelon** [comment]
Are you available for meeting ?

Can you provide your email address and available time ?

**Comment by mswiderski** [comment]
glad to hear things moved forward, thanks for the update.

In general tasks are looked up based on approvers, meaning if you have your pipeline setting with approver or group then you need to provide this via the form or query parameters when using the direct link to task.
https://github.com/automatiko-io/automatiko-approval-task#approval-forms

So in general, using the form you need:
- provide the pipeline run name
- task name - from pipeline
- user name/email if you used approver in pipeline
- group name if you used groups in the pipeline

Additionally, if you look at the approval task created in Kubernetes you will find there is approverUrl which gives you direct link to the task. then you need to append following query param:
- `?user=username/email`  if you used approver in pipeline 
- `?group=groupname`  if you used groups in the pipeline

When you integrate this with emails the link will be fully functional and will not need to add the query param.

**Comment by rajesh-carelon** [comment]
Great!

After appending the user i am able to approve the task

![image](https://user-images.githubusercontent.com/130366002/232016724-d9e71a94-99d3-425d-b149-8fd96c613724.png)

But I need guidance on Email approval

I have provided all the parameters 
Below parameters are mandatory, Do I need to create a configmap using /template folder or only approval-email file ?
What is the below parameters mailer password and instance end ?
            - name: QUARKUS_MAILER_PASSWORD
              value: password                              
            - name: QUARKUS_AUTOMATIKO_ON_INSTANCE_END
              value: "keep" 
            - name: QUARKUS_AUTOMATIKO_TEMPLATES_FOLDER
              value: "/templates"  

Lastly Can you tell me what all the procedure I have to follow for Email intergration ?

**Comment by mswiderski** [comment]
Have a look at readme for configuring emails: https://github.com/automatiko-io/automatiko-approval-task#configure-email-server

It has also section about templates but you only need it if you want to change the default templates used for email or forms.
instance end is configuration to keep completed approvals in the system for as long as associated pipeline run is in the system. So this one should stay like that.

**Comment by mswiderski** [comment]
@rajesh-carelon have you managed to get this working?

**Comment by mswiderski** [comment]
closing due to no response from reporter
